package com.example.onlinebankingapp.enums;

public enum OTPPurpose {
    SMS_CUSTOMER_SIGN_UP,
    SMS_BANK_ACCOUNT_INSERT,
    SMS_PAYMENT_ACCOUNT_ADD_MONEY,
    SMS_TRANSFER_MONEY_TO_PA,
    SMS_TRANSFER_MONEY_TO_BA,
    SMS_SAVING_ACCOUNT_ADD_MONEY,
    SMS_SAVING_ACCOUNT_WITHDRAW_MONEY,
    EMAIL_CUSTOMER_UPDATE_PROFILE
}
